PR checker

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -21,7 +21,11 @@ jobs:
         run: |
           commit_message=$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})
           echo "Commit Message: $commit_message"
-#          regex="^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+"
+          if ! [[ #commit_message =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?:\s.+ ]]; then
+            echo "::error::The commit message does not follow the conventional commit format."
+            exit 1
+          fi
+      #          regex="^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+"
 #          if [[ ! $commit_message =~ $regex ]]; then
 #            echo "::error::The commit message does not follow the conventional commit format."
 #            exit 1
