chore: PR checker

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -36,19 +36,21 @@ jobs:
           if ! [[ "${{github.event.pull_request.title}}" =~ $REGEX ]]; then
             echo "::error::The PR title does not follow the conventional commit format."
 
-            curl -L \
-            -X POST \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            --location "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ github.event.pull_request.head.sha }}" \
-            -d '{"state":"failure","description":"The PR title check is failed!","context":"ci-pr-check"}'
+#            curl -L \
+#            -X POST \
+#            -H "Accept: application/vnd.github+json" \
+#            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
+#            -H "X-GitHub-Api-Version: 2022-11-28" \
+#            --location "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ github.event.pull_request.head.sha }}" \
+#            -d '{"state":"failure","description":"The PR title check is failed!","context":"ci-pr-check"}'
           fi
 
       - name: Check branch for merging to 'main'
         run: |
           if [[ ${{ github.ref }} != 'refs/heads/develop' ]]; then
             echo "::error::Only 'develop' branch can be merged into 'main'."
+            
+            exit 1
           
             curl -L \
             -X POST \
@@ -64,6 +66,8 @@ jobs:
           if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
             echo "::error::Only branches other than 'main' can be merged into 'develop'."
           
+            exit 1
+          
             curl -L \
             -X POST \
             -H "Accept: application/vnd.github+json" \
@@ -73,12 +77,12 @@ jobs:
             -d '{"state":"failure","description":"The PR message check failed. Only branches other than 'main' can be merged into 'develop'","context":"ci-pr-check"}'
           fi
 
-      - name: set status to done
-        run: |
-          curl -L \
-          -X POST \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
-          -H "X-GitHub-Api-Version: 2022-11-28" \
-          --location "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ github.event.pull_request.head.sha }}" \
-          -d '{"state":"success","description":"The PR message check is done","context":"ci-pr-check"}'
+#      - name: set status to done
+#        run: |
+#          curl -L \
+#          -X POST \
+#          -H "Accept: application/vnd.github+json" \
+#          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
+#          -H "X-GitHub-Api-Version: 2022-11-28" \
+#          --location "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ github.event.pull_request.head.sha }}" \
+#          -d '{"state":"success","description":"The PR message check is done","context":"ci-pr-check"}'
