chore: PR checker

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -26,31 +26,24 @@ jobs:
            https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ github.event.pull_request.head.sha }} \
            -d '{"state":"pending","description":"The PR message check is failed!","context":"ci-pr-check"}'
 
-      - name: Check PR commit message
+      - name: Check PR title check
         run: |
           echo "PR SHA: $GITHUB_SHA"
           echo "Title: ${{github.event.pull_request.title}}"
-          
-          commit_message=$(curl -L \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-          --location "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/${{ github.event.pull_request.head.sha }}" | jq -r '.commit.message')
-          
-          echo "Commit Message: $commit_message"
 
-#          if ! [[ $commit_message =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?:\s.+ ]]; then
-#            echo "::error::The commit message does not follow the conventional commit format."
-#
-#               curl -L \
-#               -X POST \
-#               -H "Accept: application/vnd.github+json" \
-#               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
-#               -H "X-GitHub-Api-Version: 2022-11-28" \
-#               https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ github.event.pull_request.head.sha }} \
-#               -d '{"state":"failure","description":"The PR message check is failed!","context":"ci-pr-check"}'
-#
-#            exit 1
-#          fi
+          if ! [[ "${{github.event.pull_request.title}}" =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?:\s.+ ]]; then
+            echo "::error::The PR title does not follow the conventional commit format."
+
+            curl -L \
+               -X POST \
+               -H "Accept: application/vnd.github+json" \
+               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
+               -H "X-GitHub-Api-Version: 2022-11-28" \
+               https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ github.event.pull_request.head.sha }} \
+               -d '{"state":"failure","description":"The PR title check is failed!","context":"ci-pr-check"}'
+
+            exit 1
+          fi
 
       - name: Check branch for merging to 'main'
         run: |
