chore: PR checker

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -30,28 +30,26 @@ jobs:
 
       - name: Check PR commit message
         run: |
-               echo "PR SHA: $GITHUB_SHA"
-               #          commit_message=$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})
-               #          commit_message=$(git log --format=%B -n 1 $GITHUB_SHA)
-               curl -L \
-               -H "Accept: application/vnd.github+json" \
-               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
-               https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA | jq 
-               echo "Commit Message: $commit_message"
-          
-          #          if ! [[ $commit_message =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?:\s.+ ]]; then
-          #            echo "::error::The commit message does not follow the conventional commit format."
-          #
-               curl -L \
-               -X POST \
-               -H "Accept: application/vnd.github+json" \
-               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
-               -H "X-GitHub-Api-Version: 2022-11-28" \
-               https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ github.event.pull_request.head.sha }} \
-               -d '{"state":"failure","description":"The PR message check is failed!","context":"ci-pr-check"}'
-      #
-      #            exit 1
-      #          fi
+          echo "PR SHA: $GITHUB_SHA"
+          curl -L \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
+          https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA | jq 
+          echo "Commit Message: $commit_message"
+
+#          if ! [[ $commit_message =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?:\s.+ ]]; then
+#            echo "::error::The commit message does not follow the conventional commit format."
+#
+#               curl -L \
+#               -X POST \
+#               -H "Accept: application/vnd.github+json" \
+#               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
+#               -H "X-GitHub-Api-Version: 2022-11-28" \
+#               https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ github.event.pull_request.head.sha }} \
+#               -d '{"state":"failure","description":"The PR message check is failed!","context":"ci-pr-check"}'
+#
+#            exit 1
+#          fi
 
       - name: Check branch for merging to 'main'
         run: |
